### ISSUE TITLE
Purificateur insertion

### ISSUE THREAD

**Issue by Jules4515** [nicofighter45/FabricVanaMod#2]
Pour le purificateur

Le joueur n'est pas full inventaire

Le shift click avec les trois sortes de raw marche que dans les trois premiers slots de l'inventaire mais,  rempli avant un stack de l'item en question dans l'inventaire (si le joueur a plus d'un stack) et met juste le surplus dans la machine.
Le shift clic avec les water bucket marche mais met le water bucket dans le slot des raw, mais quand ce slot est rempli de raw on peut shift click les water bucket directement dans le slot de water bucket.
Le shift click avec tous les items ne marche que dans les trois premier slots de l'inventaire et fonctionne de la même manière qu'avec les raw (ne met que le surplus dans le machine si le joueur a plus d'un stack).
L'automatisation fonctionne bien sauf pour les water bucket, ca fonctionne que pour les 4 premiers water bucket mais quand la machine et en marche et consomme de la water, les water bucket dans le slot de bucket ne se déversent pas dans la machine, ca ne s'actualise pas.

Dans le cas où le joueur est full inventaire:

le shift click marche nickel (pour tous les items) dans tous les slots de l'inventaire et dans les trois premiers de la hotbar. 
Dans les 6 derniers slots de la hotbar, le shift click ne marche pas, il faut faire shift + double click mais ne marche pas dans les deux sens pour recup l'item de la machine en shift cliquant, ou en shift double cliquant, ça ne marche pas. Dans le cas ou le shift double click marche (dans les 6 derniers slots de la hotbar) , par exemple si on shift double click sur un raw iron dans le 9e slot, et qu'on en a aussi dans le 4e et le 5e, ca va envoyer le premier dans les 6 derniers slot de la hotbar, donc le 4e.

**Comment by nicofighter45** [comment]
Le bug provient de AbstractMachineScreenHandler dans la méthode transferSlot, l'index des slots du screen sont les derniers car ils ont été register en dernier, il faut juste modifier certains nombres pour que ça match avec la nouvelle méthode de création du screen handler
